// commands/completion.ts — generate shell tab completion script

export async function runCompletion(args: string[]): Promise<void> {
  const shell = args.includes("--zsh") ? "zsh" : "bash";

  if (args.includes("--help")) {
    console.log("Usage: draft completion [--bash | --zsh]");
    console.log("");
    console.log("Generate a shell completion script and add it to your shell config:");
    console.log("  bash:  draft completion >> ~/.bashrc && source ~/.bashrc");
    console.log("  zsh:   draft completion --zsh >> ~/.zshrc && source ~/.zshrc");
    process.exit(0);
  }

  if (shell === "zsh") {
    process.stdout.write(zshCompletion());
  } else {
    process.stdout.write(bashCompletion());
  }
}

// ── Bash completion ────────────────────────────────────────────────────────────

function bashCompletion(): string {
  return `# Draft CLI bash completion
# Generated by: draft completion
# Add to ~/.bashrc:  draft completion >> ~/.bashrc && source ~/.bashrc

_draft_completion() {
  local cur prev commands
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"
  commands="status start stop add switch profiles publish load logs proposals doctor completion uninstall"

  case "\$prev" in
    draft)
      COMPREPLY=( $(compgen -W "\$commands" -- "\$cur") )
      return 0
      ;;
    add)
      COMPREPLY=( $(compgen -W "claude-code codex cursor" -- "\$cur") )
      return 0
      ;;
    switch)
      # Complete with profile names from ~/.draft/workspaces/
      local profiles=""
      if [ -d "\$HOME/.draft/workspaces" ]; then
        profiles=$(ls "\$HOME/.draft/workspaces" 2>/dev/null)
      fi
      COMPREPLY=( $(compgen -W "\$profiles" -- "\$cur") )
      return 0
      ;;
    profiles)
      COMPREPLY=( $(compgen -W "list create rename delete" -- "\$cur") )
      return 0
      ;;
    logs)
      COMPREPLY=( $(compgen -W "--follow --errors" -- "\$cur") )
      return 0
      ;;
    completion)
      COMPREPLY=( $(compgen -W "--bash --zsh" -- "\$cur") )
      return 0
      ;;
  esac

  COMPREPLY=( $(compgen -W "\$commands" -- "\$cur") )
}

complete -F _draft_completion draft
`;
}

// ── Zsh completion ─────────────────────────────────────────────────────────────

function zshCompletion(): string {
  return `# Draft CLI zsh completion
# Generated by: draft completion --zsh
# Add to ~/.zshrc:  draft completion --zsh >> ~/.zshrc && source ~/.zshrc

_draft() {
  local state

  _arguments \\
    '1: :->command' \\
    '*: :->args'

  case \$state in
    command)
      local commands=(
        'status:Show daemon status and integration health'
        'start:Start the background daemon'
        'stop:Stop the background daemon'
        'add:Add Draft to a CLI tool'
        'switch:Activate a named profile'
        'profiles:Manage profiles'
        'publish:Push context to shared team repo'
        'load:Pull team context from shared repo'
        'logs:Tail daemon logs'
        'proposals:Review AI-generated context proposals'
        'doctor:Diagnose configuration and dependency issues'
        'completion:Generate shell completion script'
        'uninstall:Remove all of Draft and configuration'
      )
      _describe 'command' commands
      ;;
    args)
      case \$words[2] in
        add)
          local tools=('claude-code:Add Draft to Claude Code' 'codex:Add Draft to Codex' 'cursor:Add Draft to Cursor')
          _describe 'tool' tools
          ;;
        switch)
          local profiles
          profiles=(\${(f)"\$(ls \$HOME/.draft/workspaces 2>/dev/null)"})
          _describe 'profile' profiles
          ;;
        profiles)
          local subcmds=('list:List all profiles' 'create:Create a new profile' 'rename:Rename a profile' 'delete:Delete a profile')
          _describe 'subcommand' subcmds
          ;;
        logs)
          _arguments '--follow[Stream logs live]' '--errors[Show stderr log]'
          ;;
        completion)
          _arguments '--bash[Generate bash completion]' '--zsh[Generate zsh completion]'
          ;;
      esac
      ;;
  esac
}

compdef _draft draft
`;
}
