// commands/completion.ts — generate shell tab completion script

export async function runCompletion(args: string[]): Promise<void> {
  const shell = args.includes("--zsh") ? "zsh" : "bash";

  if (args.includes("--help")) {
    console.log("Usage: draft completion [--bash | --zsh]");
    console.log("");
    console.log("Generate a shell completion script and add it to your shell config:");
    console.log("  bash:  draft completion >> ~/.bashrc && source ~/.bashrc");
    console.log("  zsh:   draft completion --zsh >> ~/.zshrc && source ~/.zshrc");
    process.exit(0);
  }

  if (shell === "zsh") {
    process.stdout.write(zshCompletion());
  } else {
    process.stdout.write(bashCompletion());
  }
}

// ── Bash completion ────────────────────────────────────────────────────────────

function bashCompletion(): string {
  return `# Draft CLI bash completion
# Generated by: draft completion
# Add to ~/.bashrc:  draft completion >> ~/.bashrc && source ~/.bashrc

_draft_completion() {
  local cur prev commands
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[COMP_CWORD-1]}"
  commands="add auth context sessions integrations update completion"

  case "\$prev" in
    draft)
      COMPREPLY=( $(compgen -W "\$commands" -- "\$cur") )
      return 0
      ;;
    add)
      COMPREPLY=( $(compgen -W "claude-code codex cursor openclaw hermes" -- "\$cur") )
      return 0
      ;;
    auth)
      COMPREPLY=( $(compgen -W "login logout whoami" -- "\$cur") )
      return 0
      ;;
    context)
      COMPREPLY=( $(compgen -W "list read" -- "\$cur") )
      return 0
      ;;
    sessions)
      COMPREPLY=( $(compgen -W "enable disable status list read search" -- "\$cur") )
      return 0
      ;;
    integrations)
      COMPREPLY=( $(compgen -W "list disconnect" -- "\$cur") )
      return 0
      ;;
    disconnect)
      if [[ "\${COMP_WORDS[1]}" == "integrations" ]]; then
        COMPREPLY=( $(compgen -W "github fireflies linear slack" -- "\$cur") )
        return 0
      fi
      ;;
    completion)
      COMPREPLY=( $(compgen -W "--bash --zsh" -- "\$cur") )
      return 0
      ;;
  esac

  COMPREPLY=( $(compgen -W "\$commands" -- "\$cur") )
}

complete -F _draft_completion draft
`;
}

// ── Zsh completion ─────────────────────────────────────────────────────────────

function zshCompletion(): string {
  return `# Draft CLI zsh completion
# Generated by: draft completion --zsh
# Add to ~/.zshrc:  draft completion --zsh >> ~/.zshrc && source ~/.zshrc

_draft() {
  local state

  _arguments \\
    '1: :->command' \\
    '*: :->args'

  case \$state in
    command)
      local commands=(
        'add:Add Draft to a CLI tool'
        'auth:Authenticate with the Draft control plane'
        'context:Read workspace context'
        'sessions:Manage coding session capture'
        'integrations:Manage hosted integrations'
        'update:Update the Draft CLI'
        'completion:Generate shell completion script'
      )
      _describe 'command' commands
      ;;
    args)
      case \$words[2] in
        add)
          local tools=('claude-code:Add Draft to Claude Code' 'codex:Add Draft to Codex' 'cursor:Add Draft to Cursor' 'openclaw:Add Draft to OpenClaw' 'hermes:Add Draft to Hermes')
          _describe 'tool' tools
          ;;
        auth)
          local subcmds=('login:Sign in' 'logout:Sign out' 'whoami:Show the current identity')
          _describe 'subcommand' subcmds
          ;;
        context)
          local subcmds=('list:List available context dimensions' 'read:Print one or more context dimensions')
          _describe 'subcommand' subcmds
          ;;
        sessions)
          local subcmds=('enable:Enable session capture' 'disable:Disable session capture' 'status:Show capture status' 'list:List sessions' 'read:Read a session' 'search:Search sessions')
          _describe 'subcommand' subcmds
          ;;
        integrations)
          if (( CURRENT == 3 )); then
            local subcmds=('list:List hosted integrations' 'disconnect:Disconnect a hosted integration')
            _describe 'subcommand' subcmds
          elif [[ \$words[3] == 'disconnect' ]]; then
            local providers=('github:GitHub' 'fireflies:Fireflies' 'linear:Linear' 'slack:Slack')
            _describe 'provider' providers
          fi
          ;;
        update)
          _arguments '--check[Check without installing]'
          ;;
        completion)
          _arguments '--bash[Generate bash completion]' '--zsh[Generate zsh completion]'
          ;;
      esac
      ;;
  esac
}

compdef _draft draft
`;
}
