-- Better Auth's own tables (OAuth 2.1 AS for the remote MCP server — plan
-- 0053). Isolated in a dedicated schema, never exposed through PostgREST:
-- Draft's REST API (public.*, PostgREST/Supabase client) and Better Auth
-- (better_auth.*, a direct pg connection) are two separate identity systems
-- that only meet at the id-matched `better_auth.user.id = public.users.id`
-- convention, enforced by application code (the Supabase-session-bridge
-- endpoint), not a foreign key -- the two live in different schemas Postgres
-- cannot cross-reference, and not every Supabase user has a better_auth.user
-- row (see below).
--
-- No signup-time trigger populates better_auth.user. Provisioning is lazy:
-- backend/src/auth/better-auth-supabase-bridge-plugin.ts upserts the row on
-- a user's first MCP login. Most Supabase users never connect an MCP client
-- and never get a better_auth.user row at all -- don't assume one exists.
--
-- RLS is not the isolation mechanism here (these tables are never queried
-- through PostgREST, so `anon`/`authenticated` are never granted schema
-- `usage` in the first place -- that absence is the boundary). A dedicated
-- Postgres role is created for Better Auth's direct `pg` connection, scoped
-- to only this schema, least-privilege rather than reusing the `postgres`
-- superuser role the way Supabase's own internal tooling does.
--
-- Generated by calling better-auth's own `getMigrations().compileMigrations()`
-- against the real `betterAuth()` config (see backend/src/auth/better-auth.ts)
-- and verified end-to-end against a local Supabase Postgres: applied via
-- `runMigrations()`, confirmed all 12 tables land in `better_auth` (not
-- `public`) via `search_path=better_auth,public` on the connection, then
-- dropped again before this file was hand-placed here, per this repo's
-- generate-only convention for Better Auth's migrations.

create schema if not exists better_auth;

do $$
begin
  if not exists (select 1 from pg_roles where rolname = 'better_auth_service') then
    create role better_auth_service login password null;
  end if;
end
$$;

grant usage on schema better_auth to better_auth_service;
alter default privileges in schema better_auth grant all on tables to better_auth_service;
alter default privileges in schema better_auth grant all on sequences to better_auth_service;

set search_path to better_auth;

create table "user" ("id" text not null primary key, "name" text not null, "email" text not null unique, "emailVerified" boolean not null, "image" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null);

create table "session" ("id" text not null primary key, "expiresAt" timestamptz not null, "token" text not null unique, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null, "ipAddress" text, "userAgent" text, "userId" text not null references "user" ("id") on delete cascade);

create table "account" ("id" text not null primary key, "accountId" text not null, "providerId" text not null, "userId" text not null references "user" ("id") on delete cascade, "accessToken" text, "refreshToken" text, "idToken" text, "accessTokenExpiresAt" timestamptz, "refreshTokenExpiresAt" timestamptz, "scope" text, "password" text, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz not null);

create table "verification" ("id" text not null primary key, "identifier" text not null, "value" text not null, "expiresAt" timestamptz not null, "createdAt" timestamptz default CURRENT_TIMESTAMP not null, "updatedAt" timestamptz default CURRENT_TIMESTAMP not null);

create table "jwks" ("id" text not null primary key, "publicKey" text not null, "privateKey" text not null, "createdAt" timestamptz not null, "expiresAt" timestamptz, "alg" text, "crv" text);

create table "oauthClient" ("id" text not null primary key, "clientId" text not null unique, "clientSecret" text, "clientDiscoveryId" text, "disabled" boolean, "skipConsent" boolean, "enableEndSession" boolean, "subjectType" text, "scopes" jsonb, "clientCredentialsScopes" jsonb, "userId" text references "user" ("id") on delete cascade, "createdAt" timestamptz, "updatedAt" timestamptz, "name" text, "uri" text, "icon" text, "contacts" jsonb, "tos" text, "policy" text, "softwareId" text, "softwareVersion" text, "softwareStatement" text, "redirectUris" jsonb not null, "postLogoutRedirectUris" jsonb, "backchannelLogoutUri" text, "backchannelLogoutSessionRequired" boolean, "tokenEndpointAuthMethod" text, "applicationType" text, "jwks" text, "jwksUri" text, "grantTypes" jsonb, "responseTypes" jsonb, "requirePKCE" boolean, "dpopBoundAccessTokens" boolean, "referenceId" text, "metadata" jsonb);

create table "oauthResource" ("id" text not null primary key, "identifier" text not null unique, "name" text not null, "accessTokenTtl" integer, "refreshTokenTtl" integer, "signingAlgorithm" text, "signingKeyId" text, "allowedScopes" jsonb, "customClaims" jsonb, "dpopBoundAccessTokensRequired" boolean, "disabled" boolean, "createdAt" timestamptz, "updatedAt" timestamptz, "policyVersion" integer, "metadata" jsonb);

create table "oauthClientResource" ("id" text not null primary key, "clientId" text not null references "oauthClient" ("clientId") on delete cascade, "resourceId" text not null references "oauthResource" ("identifier") on delete cascade, "metadata" jsonb, "createdAt" timestamptz);

create table "oauthRefreshToken" ("id" text not null primary key, "token" text not null unique, "clientId" text not null references "oauthClient" ("clientId") on delete cascade, "sessionId" text references "session" ("id") on delete set null, "userId" text not null references "user" ("id") on delete cascade, "referenceId" text, "authorizationCodeId" text, "resources" jsonb, "requestedUserInfoClaims" jsonb, "expiresAt" timestamptz not null, "createdAt" timestamptz not null, "revoked" timestamptz, "rotatedAt" timestamptz, "rotationReplayResponse" text, "rotationReplayExpiresAt" timestamptz, "authTime" timestamptz, "confirmation" jsonb, "scopes" jsonb not null);

create table "oauthAccessToken" ("id" text not null primary key, "token" text not null unique, "clientId" text not null references "oauthClient" ("clientId") on delete cascade, "sessionId" text references "session" ("id") on delete set null, "userId" text references "user" ("id") on delete cascade, "referenceId" text, "authorizationCodeId" text, "resources" jsonb, "requestedUserInfoClaims" jsonb, "refreshId" text references "oauthRefreshToken" ("id") on delete cascade, "expiresAt" timestamptz not null, "createdAt" timestamptz not null, "revoked" timestamptz, "confirmation" jsonb, "scopes" jsonb not null);

create table "oauthConsent" ("id" text not null primary key, "clientId" text not null references "oauthClient" ("clientId") on delete cascade, "userId" text references "user" ("id") on delete cascade, "referenceId" text, "resources" jsonb, "requestedUserInfoClaims" jsonb, "scopes" jsonb not null, "createdAt" timestamptz not null, "updatedAt" timestamptz not null);

create table "oauthClientAssertion" ("id" text not null primary key, "expiresAt" timestamptz not null);

create index "session_userId_idx" on "session" ("userId");

create index "account_userId_idx" on "account" ("userId");

create index "verification_identifier_idx" on "verification" ("identifier");

create index "oauthClient_userId_idx" on "oauthClient" ("userId");

create index "oauthClientResource_clientId_idx" on "oauthClientResource" ("clientId");

create index "oauthClientResource_resourceId_idx" on "oauthClientResource" ("resourceId");

create index "oauthRefreshToken_clientId_idx" on "oauthRefreshToken" ("clientId");

create index "oauthRefreshToken_sessionId_idx" on "oauthRefreshToken" ("sessionId");

create index "oauthRefreshToken_userId_idx" on "oauthRefreshToken" ("userId");

create index "oauthRefreshToken_authorizationCodeId_idx" on "oauthRefreshToken" ("authorizationCodeId");

create index "oauthAccessToken_clientId_idx" on "oauthAccessToken" ("clientId");

create index "oauthAccessToken_sessionId_idx" on "oauthAccessToken" ("sessionId");

create index "oauthAccessToken_userId_idx" on "oauthAccessToken" ("userId");

create index "oauthAccessToken_authorizationCodeId_idx" on "oauthAccessToken" ("authorizationCodeId");

create index "oauthAccessToken_refreshId_idx" on "oauthAccessToken" ("refreshId");

create index "oauthConsent_clientId_idx" on "oauthConsent" ("clientId");

create index "oauthConsent_userId_idx" on "oauthConsent" ("userId");

create unique index "oauthClientResource_clientId_resourceId_uidx" on "oauthClientResource" ("clientId", "resourceId");

reset search_path;

grant all on all tables in schema better_auth to better_auth_service;
grant all on all sequences in schema better_auth to better_auth_service;

-- Extend agent_query_log's command constraint for the read-only MCP tool
-- surface (context.list/read were also missing entirely -- workspace-context.ts's
-- REST route never logged before this; see services/workspace-context-service.ts).
alter table agent_query_log drop constraint agent_query_log_command_check;
alter table agent_query_log add constraint agent_query_log_command_check
  check (command in (
    'sessions.list', 'sessions.read', 'sessions.search',
    'skills.list', 'skills.read',
    'context.read',
    'mcp.context.list', 'mcp.context.read',
    'mcp.sessions.list', 'mcp.sessions.read', 'mcp.sessions.search',
    'mcp.skills.list', 'mcp.skills.read'
  ));
